server:
  port: 8080

spring:
  application:
    name: active-passive-api

resilience4j:
  circuitbreaker:
    instances:
      customerService:
        register-health-indicator: true
        sliding-window-size: 5
        sliding-window-type: COUNT_BASED
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state:
          seconds: 5s
        event-consumer-buffer-size: 10
        record-exceptions:
          - java.lang.RuntimeException